{% set version = "4.7.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-breakaway
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/breakaway_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/breakaway/breakaway_{{ version }}.tar.gz
  sha256: 11019e462415619fa56af60c92d574e2d29e57cfcaf554afc209fad929183691

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-ggplot2
    - r-lme4
    - r-magrittr
    - r-phyloseq
    - r-tibble
  run:
    - r-base
    - r-mass
    - r-ggplot2
    - r-lme4
    - r-magrittr
    - r-phyloseq
    - r-tibble

test:
  commands:
    - $R -e "library('breakaway')"           # [not win]
    - "\"%R%\" -e \"library('breakaway')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=breakaway
  license: GPL-2.0-only
  summary: Species richness estimation is an important problem in biodiversity analysis. This package provides methods for total species richness estimation (observed plus unobserved) and a method for modelling total diversity with covariates. breakaway() estimates total (observed plus unobserved) species richness. Microbial
    diversity datasets are characterized by a large number of rare species and a small number of highly abundant species. The class of models implemented by breakaway() is flexible enough to model both these features. breakaway_nof1() implements a similar procedure however does not require a singleton count. betta() provides
    a method for modelling total diversity with covariates in a way that accounts for its estimated nature and thus accounts for unobserved taxa, and betta_random() permits random effects modelling.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: breakaway
# Title: Species Richness Estimation and Modeling
# Version: 3.0
# Date: 2016-03-29
# Author: Amy Willis and John Bunge
# Maintainer: Amy Willis <adw96@cornell.edu>
# Description: Species richness estimation is an important problem in biodiversity analysis. This package provides methods for total species richness estimation (observed plus unobserved) and a method for modelling total diversity with covariates. breakaway() estimates total (observed plus unobserved) species richness. Microbial diversity datasets are characterized by a large number of rare species and a small number of highly abundant species. The class of models implemented by breakaway() is flexible enough to model both these features. breakaway_nof1() implements a similar procedure however does not require a singleton count. betta() provides a method for modelling total diversity with covariates in a way that accounts for its estimated nature and thus accounts for unobserved taxa, and betta_random() permits random effects modelling.
# License: GPL-2
# NeedsCompilation: no
# Packaged: 2016-03-30 02:48:44 UTC; adw96
# Repository: CRAN
# Date/Publication: 2016-03-30 08:14:27
