appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: YuA/tfiPWBfL5jPTRB0mkAsZWvI/g2JdFWxJIY0bIADua6BIQl0lAZsW4Q6Vf8KwlGKEPlcbvVi0L+BEsCkr+SJohBZfc8qM9+eKFZJY9730dGt1yC88z7DR9SjwdeJP6kfMjFgY9Bpgtv86LITU3V3mOZyOhBdkfevEXYqORDLp1J6MCY/JoPc7tNx4mBBlYNxN1Evo+zuLO2s2U7Le+51gQCXiU3qqVel2IyfoNkkREhvhA2aN3PXvZYR2KJXaBMzJAEdodYCCxSgESXmFP16ZWl4Db4deBJUHisCJwd8dXvcYEewidH5YXn3clfHs1t20uVTvFRlFgPi0Zb2cDl5at/24ZTFFGaoocqgOEFIdRvnthp32x+gqKWr7pTZcT8XUp4pQoo4LCQ9fRqsZHh0j4op5aQFM3WPlNmQSPukyp/wIb4f2uW9T4Ya+Bcsdnz0qQaRbTVcbhY7UyupoL7ZMnoistrSioHX4a8Jc6ugq5XlKTkicDUa5gOcfedamIe8vwnLp8m/H7weqCJy6VpA70D7UDEffEfYmhnUbJe/8fSVFjyDos1h1a/Za+Mf9+4EFplgSY3lfys/TxWzS3EqfKKG0PKDZ9A25DGlfEAelRHI2sGJY2LfQ5ZMpy9L3Uol++RFukGn2fRgbcIeaFOPi+iCTeMZQZN5cdIljFNM=
conda_forge_output_validation: true
